version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${DB_USER} -d $${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      postgresdb:
        condition: service_healthy
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - '5555:5555'
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgresdb:${DB_DOCKER_PORT}/${DB_NAME}?schema=public
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
      - NODE_ENV=$NODE_ENV
    stdin_open: true
    tty: true
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80' # HTTP
      - '443:443' # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # SSL 인증서
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
